config/routes.rb
Resolute::Application.routes.draw do 
  resources :tournament_pages do
    collection do
      get :admin, :as => :admin
      post :sort
      get :registration, :as => :registration
    end
  end

  resources :club_teams, :except => [:show] do
    collection do
      get :admin, :as => :admin
      post :sign_up, :as => :sign_up
      get :registrants, :as => :registrants
    end
  end
  match "/club_teams/(/:parent_slug(/:child_slug))" => "club_teams#show"

  devise_for :players

  resources :panels do
    collection do
      get :admin, :as => :admin
      post :updating, :as => :updating
    end
  end

  resources :tournament_entries, :except => [:update]

  resources :stats

  resources :staff_members, :except => [:show] do
    collection do
      get :admin, :as => :admin
      post :sort
    end
  end

  resources :camps, :except => [:index] do
    collection do
      get :admin, :as => :admin
    end
  end

  match "/camps-clinics(/:year(/:month))" => "camps#index",
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :coach_clinic_registrations

  resources :items, :except => [:index] do
    collection do
      get :pages, :as => :pages
      get :categories, :as => :categories
      get :mailchimp, :as => :mailchimp
    end
  end

  resources :products
  resources :contest_entries, :only => [:new, :create, :index, :destroy]
  resources :contacts, :only => [:new, :create]
  resources :pages, :controller => :items
  resources :camp_registrations

  resources :categories, :controller => :items do
    collection do
      post :sort
    end
  end

  devise_for :users

  match '/midwest-classic-youth-tournament' => 'tournament_pages#index'
  match '/club-teams' => 'club_teams#index'
  match '/admin' => 'admin#index', :as => :admin
  match '/home', :to => redirect("/")
  match '/videos' => 'items#videos', :as => :videos
  match '/contact-us' => 'contacts#new'
  match '/store' => 'products#store', :as => :store
  match '/staff' => 'staff_members#index', :as => :staff

  match ':id' => 'items#show', :as => :pretty_url

   root :to => "panels#index"

end

app/models/club_team.rb
class ClubTeam < ActiveRecord::Base
  before_validation :update_slug
  scope :main_pages, where(:general_page != true).where(:parent_id => nil).order("created_at DESC")
  scope :general_pages, where(:general_page => true).order("created_at ASC")

  validates_uniqueness_of :name, :scope => :parent_id

  def children
    ClubTeam.where(:parent_id => id).order("created_at DESC")
  end

  def parent
    ClubTeam.where(:id => parent_id).first
  end

  def general_page?
    general_page == true
  end

  private 

  def update_slug
    self.slug = self.name.parameterize
  end
end

app/controllers/club_teams_controller.rb
class ClubTeamsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index, :sign_up]

  def admin
    if params[:general_pages]
      @club_teams = ClubTeam.general_pages
    else
      @club_teams = ClubTeam.main_pages
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @club_teams }
    end
  end

  # GET /club_teams
  # GET /club_teams.xml
  def index
    @club_team = ClubTeam.general_pages.first
    render :show
  end

  # GET /club_teams/1
  # GET /club_teams/1.xml
  def show
    @club_team = parent = ClubTeam.find_by_slug(params[:parent_slug])
    @registration = ClubTeamRegistration.new
    
    unless params[:child_slug].nil?
      @club_team = ClubTeam.find_by_slug_and_parent_id(params[:child_slug], parent.id)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @club_team }
    end
  end

  # GET /club_teams/new
  # GET /club_teams/new.xml
  def new
    @club_team = ClubTeam.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @club_team }
    end
  end

  # GET /club_teams/1/edit
  def edit
    @club_team = ClubTeam.find_by_id(params[:id])
  end

  # POST /club_teams
  # POST /club_teams.xml
  def create
    @club_team = ClubTeam.new(params[:club_team])

    if params[:general_page]
      @club_team.general_page = true
    else
      @club_team.general_page = false
    end

    respond_to do |format|
      if @club_team.save
        if @club_team.general_page?
          format.html { redirect_to(admin_club_teams_path(:general_pages => true), :notice => 'Club team was successfully created.') }
        else
          format.html { redirect_to(admin_club_teams_path, :notice => 'Club team was successfully created.') }
        end
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /club_teams/1
  # PUT /club_teams/1.xml
  def update
    @club_team = ClubTeam.find_by_id(params[:id])

    respond_to do |format|
      if @club_team.update_attributes(params[:club_team])
        if @club_team.general_page?
          format.html { redirect_to(admin_club_teams_path(:general_pages => true), :notice => 'Club team was successfully updated.') }
        else
          format.html { redirect_to(admin_club_teams_path, :notice => 'Club team was successfully updated.') }
        end
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @club_team.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /club_teams/1
  # DELETE /club_teams/1.xml
  def destroy
    @club_team = ClubTeam.find_by_id(params[:id])
    general_page = @club_team.general_page?
    @club_team.destroy

    respond_to do |format|
      if general_page
        format.html { redirect_to(admin_club_teams_url(:general_pages => true)) }
      else
        format.html { redirect_to(admin_club_teams_url) }
      end
    end
  end

  def registrants
    @registrants = ClubTeamRegistration.all
  end

  def sign_up
    @registration = ClubTeamRegistration.new(params[:club_team_registration])

    respond_to do |format|
      if @registration.save
        session[:registration_errors] = nil
        format.html { redirect_to(:back, :notice => 'Thank you for registering for the club teams! We will be in contact with you shortly.') }
      else
        session[:registration_errors] = @registration.errors
        format.html { redirect_to(:back, :error => "Failed to register. Please try again!") }
      end
    end
  end
end

app/helpers/club_teams_helper.rb
module ClubTeamsHelper
  def even?(index)
    index % 2 == 0
  end

  def confine_to_background(team_name)
    truncate(word_wrap(team_name, :line_width => 21), :length => 82)
  end

  def club_team_links(page)
    output = ""
    output << "<ul>"
    if page.is_a?(ActiveRecord::Relation)
      page.each do |club_team|
        output << "<hr width = '100%' style = 'height: 1px; color: black;' />"
        output << "<li><a href=\"/club_teams/#{club_team.slug}\">#{club_team.name}</a></li>"
      end
    else
      if page.parent_id.nil?
        output << "<li><a href=\"/club_teams/#{page.slug}\">#{page.name}</a></li>"

        page.children.each do |club_team|
          output << "<hr width = '100%' style = 'height: 1px; color: black;' />"
          output << "<li><a href=\"/club_teams/#{club_team.parent.slug}/#{club_team.slug}\">#{club_team.name}</a></li>"
        end unless page.children.empty?
      else
        output << "<li><a href=\"/club_teams/#{page.parent.slug}\">#{page.parent.name}</a></li>"

        page.parent.children.each do |club_team|
          output << "<hr width = '100%' style = 'height: 1px; color: black;' />"
          output << "<li><a href=\"/club_teams/#{club_team.parent.slug}/#{club_team.slug}\">#{club_team.name}</a></li>"
        end unless page.parent.nil? || page.parent.children.nil?
      end
    end

    output << "</ul>"
    raw(output.html_safe)
  end

  def all_club_teams
    ClubTeam.main_pages.collect { |team| [team.name, team.id] }
  end

  def club_team_title
    return @club_team.parent.name unless @club_team.parent.nil?
    @club_team.name
  end

  def is_a_general_page?
    params[:general_page] || @club_team.general_page
  end

  def positions
    ["Attack", "Middle", "Defense", "Goalie"]
  end

  def grad_year
    [2013, 2014, 2015, 2016, 2017]
  end

  def state_abbreviations
    states = []
    states = %w[AL AK AS AZ AR CA CO CT DE DC FM FL GA GU HI ID IL IN IA KS KY LA ME MH MD MA
                MI MN MS MO MT NE NV NH NJ NM NY NC ND MP OH OK OR PW PA PR RI SC SD TN TX UT
                VT VI VA WA WV WI WY].map{|state| [state, state]}
  end
end

app/views/club_teams/_form.html.haml
= form_for(@club_team) do |f|
  - if @club_team.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@club_team.errors.count, 'error')} prohibited this club team from being saved:"
      %ul
      - @club_team.errors.full_messages.each do |msg|
        %li= msg
  
  .field
    - if is_a_general_page?
      = hidden_field_tag :general_page, true
    - else
      = hidden_field_tag :general_page, false

  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :information
    %br
    = f.cktext_area :information, :width => "80%", :height => "600px"

    - unless is_a_general_page?
      .field
        = f.label :parent
        %br
        = f.select :parent_id, all_club_teams, { :include_blank => true }

  - if is_a_general_page?
    .field
      = f.label :show_registration_form
      %br
      = f.check_box :show_registration_form

  .actions
    = f.submit

app/views/club_teams/_nav.html.haml
#club-team.sidebar
  = club_team_links(nav)

app/views/club_teams/_registration.html.haml
= form_for @registration, :url => sign_up_club_teams_path(@registration) do |f|

  - unless session[:registration_errors] == nil
    #error_explanation
      %h2
        = pluralize(session[:registration_errors].values.flatten.count, "error")
        prohibited this registration from being saved:
      %ul
        - session[:registration_errors].each do |msg|
          %li= msg.first.to_s.humanize + " " + msg.second

  .field
    = f.label :first_name
    %br/
    = f.text_field :first_name

  .field
    = f.label :last_name
    %br/
    = f.text_field :last_name

  .field
    = f.label :primary_email
    %br/
    = f.text_field :primary_email

  .field
    = f.label :secondary_email
    %br/
    = f.text_field :secondary_email

  .field
    = f.label :street_address
    %br/
    = f.text_field :street_address
  .field
    = f.label :city
    %br/
    = f.text_field :city
  .field
    = f.label :state
    %br/
    = f.select :state, state_abbreviations, {:include_blank => true}
  .field
    = f.label :zip
    %br/
    = f.text_field :zip, :size => 5

  .field
    = f.label :age
    %br/
    = f.text_field :age, :size => 2

  .field
    = f.label :position
    %br/
    = f.select :position, positions, {:include_blank => true}

  .field
    = f.label :school
    %br/
    = f.text_field :school

  .field
    = f.label :graduation_year
    %br/
    = f.select :graduation_year, grad_year, {:include_blank => true}

  .field
    = f.label :primary_phone
    %br/
    = f.text_field :primary_phone, :size => 14

  .field
    = f.label :secondary_phone
    %br/
    = f.text_field :secondary_phone, :size => 14

  .actions
    = f.submit "Sign Up"

app/views/club_teams/admin.html.haml
#title Club Teams

%table{:width => "100%"}
  %thead
    %th Name
    %th
    %th
    %th
  %tbody
    - @club_teams.each do |club_team|
      %tr{:style => "margin: 10px 0 10px 0;"}
        %td= raw "<b>#{club_team.name}</b>"
        %td= link_to 'Show', "/club_teams/#{club_team.slug}"
        %td= link_to 'Edit', edit_club_team_path(club_team)
        %td= link_to 'Destroy', club_team, :confirm => 'Are you sure?', :method => :delete
      - club_team.children.each do |child|
        %tr
          %td= child.name
          %td= link_to 'Show', "/club_teams/#{club_team.slug}/#{child.slug}"
          %td= link_to 'Edit', edit_club_team_path(child)
          %td= link_to 'Destroy', club_team, :confirm => 'Are you sure?', :method => :delete
  %br/
%br/

- if params[:general_pages]
  = link_to 'New Club Team', new_club_team_path(:general_page => true)
- else
  = link_to 'New Club Team', new_club_team_path

app/views/club_teams/edit.html.haml
#title Edit Club Team
= render 'form'
%br/
= link_to :back

app/views/club_teams/index.html.haml
#title Club Teams

= render :partial => "nav", :object => @general_pages

#club-team.content

  #club-teams
    - @list.each do |club_team|
      #club-team-box
        %div{ :class => cycle(:one, :two) }= link_to confine_to_background(club_team.name), "/club_teams/#{club_team.slug}"

app/views/club_teams/new.html.haml
#title New Club Team
= render 'form'
%br/
= link_to :back

app/views/club_teams/registrants.html.haml
%table{:cellspacing => "10"}
  %tr{:style => "background-color: #97BFDE;"}
    %th First Name
    %th Last Name
    %th Age
    %th Position
    %th Primary Email
    %th Secondary Email
    %th Primary Phone
    %th Secondary Phone
    %th School
    %th Street Address
    %th City
    %th State
    %th Zip
    %th Graduation Year

    - @registrants.each do |reg|
      %tr{:style => "background-color: gray;"}
        %td= reg.first_name
        %td= reg.last_name
        %td= reg.age
        %td= reg.position
        %td= reg.primary_email
        %td= reg.secondary_email
        %td= reg.primary_phone
        %td= reg.secondary_phone
        %td= reg.school
        %td= reg.street_address
        %td= reg.city
        %td= reg.state
        %td= reg.zip
        %td= reg.graduation_year
  %br
  %br
  %br
%br
= link_to :back

app/views/club_teams/show.html.haml
#title= club_team_title

- if is_a_general_page?
  = render :partial => "nav", :object => ClubTeam.general_pages
- else
  = render :partial => "nav", :object => @club_team

#club-team.content
  = raw(@club_team.information)

#club-team.content{:style => "float: right;"}
  - if @club_team.show_registration_form?
    #new_camp_registration
      #title Register For Open Tryouts
      = render :partial => "registration", :object => @registration