config/routes.rb
Resolute::Application.routes.draw do 
  resources :tournament_pages do
    collection do
      get :admin, :as => :admin
      post :sort
      get :registration, :as => :registration
    end
  end

  resources :club_teams, :except => [:show] do
    collection do
      get :admin, :as => :admin
      post :sign_up, :as => :sign_up
      get :registrants, :as => :registrants
    end
  end
  match "/club_teams/(/:parent_slug(/:child_slug))" => "club_teams#show"

  devise_for :players

  resources :panels do
    collection do
      get :admin, :as => :admin
      post :updating, :as => :updating
    end
  end

  resources :tournament_entries, :except => [:update]

  resources :stats

  resources :staff_members, :except => [:show] do
    collection do
      get :admin, :as => :admin
      post :sort
    end
  end

  resources :camps, :except => [:index] do
    collection do
      get :admin, :as => :admin
    end
  end

  match "/camps-clinics(/:year(/:month))" => "camps#index",
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :coach_clinic_registrations

  resources :items, :except => [:index] do
    collection do
      get :pages, :as => :pages
      get :categories, :as => :categories
      get :mailchimp, :as => :mailchimp
    end
  end

  resources :products
  resources :contest_entries, :only => [:new, :create, :index, :destroy]
  resources :contacts, :only => [:new, :create]
  resources :pages, :controller => :items
  resources :camp_registrations

  resources :categories, :controller => :items do
    collection do
      post :sort
    end
  end

  devise_for :users

  match '/midwest-classic-youth-tournament' => 'tournament_pages#index'
  match '/club-teams' => 'club_teams#index'
  match '/admin' => 'admin#index', :as => :admin
  match '/home', :to => redirect("/")
  match '/videos' => 'items#videos', :as => :videos
  match '/contact-us' => 'contacts#new'
  match '/store' => 'products#store', :as => :store
  match '/staff' => 'staff_members#index', :as => :staff

  match ':id' => 'items#show', :as => :pretty_url

   root :to => "panels#index"

end

app/models/camp.rb
class Camp < ActiveRecord::Base
  has_event_calendar
  acts_as_gmappable :check_process => :prevent_geocoding,
                    :address => lambda{|a| a.location },
                    :msg => "Sorry, not even Google could figure out where that is"

  validates_presence_of :name, :start_at, :end_at, :description, :location, :group, :cost, :payment_url
  validates_numericality_of :cost
  validates_uniqueness_of :name
  validates_format_of :payment_url, :with => /^(https:\/\/www.paypal.com\/)(.+)$/, :message => "must start with 'https://www.paypal.com/'"
  
  before_save :update_slug

  has_one :registration_form
  has_many :camp_registrations, :through => :registration_form, :dependent => :destroy

  accepts_nested_attributes_for :registration_form

  scope :high_school_camps, where{ (group == "High School") & (end_at > Time.now) }.order("start_at ASC")
  scope :junior_high_camps, where{ (group == "Junior High") & (end_at > Time.now) }.order("start_at ASC")
  scope :other_camps, where{ (group ^ "High School") & (group ^ "Junior High") & (end_at > Time.now) }.order("start_at ASC")

  def prevent_geocoding
    location.blank?
  end

  def to_param
    name.parameterize
  end

  private

  def update_slug
    self.slug = self.name.parameterize
  end

end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

  def admin
    @camps = Camp.all
  end

  def new
    @camp = Camp.new
    @camp.registration_form = RegistrationForm.new
  end

  def index
    @high_school = Camp.high_school_camps
    @junior_high = Camp.junior_high_camps
    @other_camps = Camp.other_camps

    @month = (params[:month] || Time.zone.now.month).to_i
    @year = (params[:year] || Time.zone.now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Camp.event_strips_for_month(@shown_month)
  end

  def show
    @camp = Camp.find_by_slug(params[:id])
    @camp_registration = CampRegistration.new
  end

  def edit
    @camp = Camp.find_by_slug(params[:id])
  end

  def create
    @camp = Camp.new(params[:camp])

    respond_to do |format|
      if @camp.save
        format.html { redirect_to(@camp, :notice => 'Camp was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @camp = Camp.find_by_slug(params[:id])

    respond_to do |format|
      if @camp.update_attributes(params[:camp])
        format.html { redirect_to(@camp, :notice => 'Camp was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @camp = Camp.find_by_slug(params[:id])
    @camp.destroy

    redirect_to(admin_camps_url)
  end
end

app/helpers/camps_helper.rb
module CampsHelper
  include CalendarHelper

  def formatted_datetime(datetime)
    return datetime.strftime("%B %e, %Y at %l:%M %p")
  end

  def city_and_state(camp)
    result = camp.location
    result.split(" ")[0]
  end

  def street_address(camp)
    result = camp.location
    result.split(" ")[1]
  end


  def found_resolute
    answers = []
    answers = ["Recommended", "Google Search", "Advertisement", "Other"].map{|answer| [answer, answer]}
  end

  def state_abbreviations
    states = []
    states = %w[AL AK AS AZ AR CA CO CT DE DC FM FL GA GU HI ID IL IN IA KS KY LA ME MH MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND MP OH OK OR PW PA PR RI SC SD TN TX UT VT VI VA WA WV WI WY].map{|state| [state, state]}
  end
end

app/views/camps/_form.html.haml
= form_for(@camp) do |f|
  - if @camp.errors.any?
    #error_explanation
      %h2
        = pluralize(@camp.errors.count, "error")
        prohibited this camp from being saved:
      %ul
        - @camp.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :start_at
    %br/
    = f.datetime_select :start_at, :default => Time.now
  .field
    = f.label :end_at
    %br/
    = f.datetime_select :end_at, :default => Time.now
  .field
    = f.label :description
    %br/
    = f.cktext_area :description, :width => "80%", :height => "600px"
  .field
    = f.label :location
    %br/
    = f.text_field :location
  .field
    = f.label :payment_url, "PayPal URL"
    %br/
    = f.text_field :payment_url
    %br/
    %span.subtext Use full street address.
    %br/
    = f.label :cost
    %br/
    = f.text_field :cost, :size => 6
    %br/
    %span.subtext Do not include a dollar sign.
  .field
    = f.label :group
    %br/
    = f.select :group, options_for_select(["Junior High","High School","Other"]), {:include_blank => true}
  .field
    = f.label :show_registration_form
    %br/
    = f.check_box :show_registration_form

  %h2 Registration Form
  = f.fields_for :registration_form do |reg|
    .field
      = reg.label :name
      = reg.check_box :name
    .field
      = reg.label :age
      = reg.check_box :age
    .field
      = reg.label :school
      = reg.check_box :school
    .field
      = reg.label :position
      = reg.check_box :position
    .field
      = reg.label :email
      = reg.check_box :email
    .field
      = reg.label :phone
      = reg.check_box :phone
    .field
      = reg.label :address
      = reg.check_box :address
    .field
      = reg.label :grade
      = reg.check_box :grade
    .field
      = reg.label :yrs_of_exp, "Years of Experience"
      = reg.check_box :yrs_of_exp
    .field
      = reg.label :finding_resolute
      = reg.check_box :finding_resolute
    .field
      = reg.label :shirt_size
      = reg.check_box :shirt_size
    .field
      = reg.label :gender
      = reg.check_box :gender
    .field
      = reg.label :comments
      = reg.check_box :comments

  .actions
    = f.submit

app/views/camps/admin.html.haml
#title Listing camps
%table
  %tr
    %th Name
    %th Start at
    %th End at
    %th Location
    %th Group
    %th
    %th
    %th
  - @camps.each do |camp|
    %tr
      %td= camp.name
      %td= formatted_datetime(camp.start_at)
      %td= formatted_datetime(camp.end_at)
      %td= camp.location
      %td= camp.group
      %td= link_to 'Show', camp
      %td= link_to 'Edit', edit_camp_path(camp)
      %td= link_to 'Destroy', camp, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Camp', new_camp_path

app/views/camps/edit.html.haml
#title Editing Camp
= render 'form'
= link_to 'Show', @camp
|
\#{link_to 'Back', camps_path}

app/views/camps/index.html.haml
#title
  Camps & Clinics

#camp-container
  #camp-list.blue.float-left
    #camp-list-name Youth (8th Grade and Under)
    %br/
    - if @junior_high.count.zero?
      There are no junior high camps scheduled at this time.
    - else
      - @junior_high.each do |camp|
        %b= link_to camp.name, camp_path(camp)
        %br/
        = formatted_datetime(camp.start_at)
        %br/
        = city_and_state(camp)
        %br/
        %br/
  #camp-list.gray.float-left
    #camp-list-name High School
    %br/
    - if @high_school.count.zero?
      There are no high school camps scheduled at this time.
    - else
      - @high_school.each do |camp|
        %b= link_to camp.name, camp_path(camp)
        %br/
        = formatted_datetime(camp.start_at)
        %br/
        = city_and_state(camp)
        %br/
        %br/
  #camp-list.light-gray.float-right
    #camp-list-name Other Camps
    %br/
    - if @other_camps.count.zero?
      There are no other camps scheduled at this time.
    - else
      - @other_camps.each do |camp|
        %b= link_to camp.name, camp_path(camp)
        %br/
        = formatted_datetime(camp.start_at)
        %br/
        = city_and_state(camp)
        %br/
        %br/

#calendar
  = raw(event_calendar)

= content_for :header do
  = stylesheet_link_tag "event_calendar"
  = javascript_include_tag "event_calendar"

app/views/camps/new.html.haml
#title New Camp
= render 'form'
= link_to 'Back', camps_path

app/views/camps/show.html.haml
#title= @camp.name

= gmaps("markers" => {"data" => @camp.to_gmaps4rails}, "map_options" =>  { "provider" => "openlayers"}, :id => "map")

%b Location:
%br/
= street_address(@camp)
%p
  %b Starts at:
  = formatted_datetime(@camp.start_at)
%p
  %b Ends at:
  = formatted_datetime(@camp.end_at)
%p
  %b Cost:
  = number_to_currency(@camp.cost)
%p
  = raw @camp.description

- if @camp.show_registration_form?
  #new_camp_registration
    #title Register Now!
    = render :partial => "camp_registrations/form", :object => @camp

= render :partial => "admin/admin_links"