config/routes.rb
Resolute::Application.routes.draw do 
  resources :tournament_pages do
    collection do
      get :admin, :as => :admin
      post :sort
      get :registration, :as => :registration
    end
  end

  resources :club_teams, :except => [:show] do
    collection do
      get :admin, :as => :admin
      post :sign_up, :as => :sign_up
      get :registrants, :as => :registrants
    end
  end
  match "/club_teams/(/:parent_slug(/:child_slug))" => "club_teams#show"

  devise_for :players

  resources :panels do
    collection do
      get :admin, :as => :admin
      post :updating, :as => :updating
    end
  end

  resources :tournament_entries, :except => [:update]

  resources :stats

  resources :staff_members, :except => [:show] do
    collection do
      get :admin, :as => :admin
      post :sort
    end
  end

  resources :camps, :except => [:index] do
    collection do
      get :admin, :as => :admin
    end
  end

  match "/camps-clinics(/:year(/:month))" => "camps#index",
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :coach_clinic_registrations

  resources :items, :except => [:index] do
    collection do
      get :pages, :as => :pages
      get :categories, :as => :categories
      get :mailchimp, :as => :mailchimp
    end
  end

  resources :products
  resources :contest_entries, :only => [:new, :create, :index, :destroy]
  resources :contacts, :only => [:new, :create]
  resources :pages, :controller => :items
  resources :camp_registrations

  resources :categories, :controller => :items do
    collection do
      post :sort
    end
  end

  devise_for :users

  match '/midwest-classic-youth-tournament' => 'tournament_pages#index'
  match '/club-teams' => 'club_teams#index'
  match '/admin' => 'admin#index', :as => :admin
  match '/home', :to => redirect("/")
  match '/videos' => 'items#videos', :as => :videos
  match '/contact-us' => 'contacts#new'
  match '/store' => 'products#store', :as => :store
  match '/staff' => 'staff_members#index', :as => :staff

  match ':id' => 'items#show', :as => :pretty_url

   root :to => "panels#index"

end

app/views/admin/_admin_links.html.haml
- if user_signed_in?
  #admin_links
    = link_to 'Edit', edit_item_path(@item) 
    |
    = link_to 'Back', :back
    |
    = link_to 'Admin Home', admin_path

app/views/admin/index.html.haml
#title
  Admin

= link_to 'Manage Categories', categories_items_path
%br/
= link_to 'Manage Pages', pages_items_path
%br/
= link_to 'View Contest Entries', contest_entries_path
%br/
= link_to 'View Camp Registrations', camp_registrations_path
%br/
= link_to 'Manage Store', products_path
%br/
= link_to 'Manage Camps', admin_camps_path
%br/
= link_to 'Manage Staff Members', admin_staff_members_path
%br/
= link_to 'View Tournament Entries', tournament_entries_path
%br/
= link_to 'Update Panels', admin_panels_path
%br/
= link_to 'Edit Individual Club Team Pages', admin_club_teams_path
%br/
= link_to 'Edit General Club Team Pages', admin_club_teams_path(:general_pages => true)
%br/
= link_to 'Manage Tournament Pages', admin_tournament_pages_path