config/routes.rb
Resolute::Application.routes.draw do 
  resources :tournament_pages do
    collection do
      get :admin, :as => :admin
      post :sort
      get :registration, :as => :registration
    end
  end

  resources :club_teams, :except => [:show] do
    collection do
      get :admin, :as => :admin
      post :sign_up, :as => :sign_up
      get :registrants, :as => :registrants
    end
  end
  match "/club_teams/(/:parent_slug(/:child_slug))" => "club_teams#show"

  devise_for :players

  resources :panels do
    collection do
      get :admin, :as => :admin
      post :updating, :as => :updating
    end
  end

  resources :tournament_entries, :except => [:update]

  resources :stats

  resources :staff_members, :except => [:show] do
    collection do
      get :admin, :as => :admin
      post :sort
    end
  end

  resources :camps, :except => [:index] do
    collection do
      get :admin, :as => :admin
    end
  end

  match "/camps-clinics(/:year(/:month))" => "camps#index",
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :coach_clinic_registrations

  resources :items, :except => [:index] do
    collection do
      get :pages, :as => :pages
      get :categories, :as => :categories
      get :mailchimp, :as => :mailchimp
    end
  end

  resources :products
  resources :contest_entries, :only => [:new, :create, :index, :destroy]
  resources :contacts, :only => [:new, :create]
  resources :pages, :controller => :items
  resources :camp_registrations

  resources :categories, :controller => :items do
    collection do
      post :sort
    end
  end

  devise_for :users

  match '/midwest-classic-youth-tournament' => 'tournament_pages#index'
  match '/club-teams' => 'club_teams#index'
  match '/admin' => 'admin#index', :as => :admin
  match '/home', :to => redirect("/")
  match '/videos' => 'items#videos', :as => :videos
  match '/contact-us' => 'contacts#new'
  match '/store' => 'products#store', :as => :store
  match '/staff' => 'staff_members#index', :as => :staff

  match ':id' => 'items#show', :as => :pretty_url

   root :to => "panels#index"

end

app/models/coach_clinic_registration.rb
class CoachClinicRegistration < ActiveRecord::Base
  validates_presence_of :name, :email, :program
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_uniqueness_of :email
end

app/controllers/coach_clinic_registrations_controller.rb
class CoachClinicRegistrationsController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :create]
  before_filter :find_registrations, :only => [:show, :edit, :update, :destroy]

  def index
    @coach_clinic_registrations = CoachClinicRegistration.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @coach_clinic_registrations }
    end
  end

  # GET /coach_clinic_registrations/1
  # GET /coach_clinic_registrations/1.xml
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @coach_clinic_registration }
    end
  end

  # GET /coach_clinic_registrations/new
  # GET /coach_clinic_registrations/new.xml
  def new
    @coach_clinic_registration = CoachClinicRegistration.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @coach_clinic_registration }
    end
  end

  # GET /coach_clinic_registrations/1/edit
  def edit
  end

  # POST /coach_clinic_registrations
  # POST /coach_clinic_registrations.xml
  def create
    @coach_clinic_registration = CoachClinicRegistration.new(params[:coach_clinic_registration])

    respond_to do |format|
      if @coach_clinic_registration.save
        format.html { redirect_to(new_coach_clinic_registration_path, :notice => 'Thank you for registering for the clinic! We will be in contact with you shortly.') }
      else
        format.html { render :action => "new", :error => "Failed to register for the camp. Please try again!" }
      end
    end
  end

  # PUT /coach_clinic_registrations/1
  # PUT /coach_clinic_registrations/1.xml
  def update

    respond_to do |format|
      if @coach_clinic_registration.update_attributes(params[:coach_clinic_registration])
        format.html { redirect_to(@coach_clinic_registration, :notice => 'Coach clinic registration was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @coach_clinic_registration.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /coach_clinic_registrations/1
  # DELETE /coach_clinic_registrations/1.xml
  def destroy
    @coach_clinic_registration.destroy

    respond_to do |format|
      format.html { redirect_to(coach_clinic_registrations_url) }
      format.xml  { head :ok }
    end
  end

  private

  def find_registrations
    @coach_clinic_registration = CoachClinicRegistration.find(params[:id])
  end
end

app/helpers/coach_clinic_registrations_helper.rb
module CoachClinicRegistrationsHelper
end

app/views/coach_clinic_registrations/_form.html.haml
= form_for(@coach_clinic_registration) do |f|
  - if @coach_clinic_registration.errors.any?
    #error_explanation
      %h2
        = pluralize(@coach_clinic_registration.errors.count, "error")
        prohibited this registration from being submitted:
      %ul
        - @coach_clinic_registration.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label "School/Program"
    %br/
    = f.text_field :program
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :comments
    %br/
    = f.text_area :comments
  .actions
    = f.submit "Register"

app/views/coach_clinic_registrations/edit.html.erb
<h1>Editing coach_clinic_registration</h1>

<%= render 'form' %>

<%= link_to 'Show', @coach_clinic_registration %> |
<%= link_to 'Back', coach_clinic_registrations_path %>

app/views/coach_clinic_registrations/index.html.haml
#title
  Coach Clinic Registrations

%table
  %tr
    %th Name
    %th Program
    %th Email
    %th Comments
    %th
    %th
    %th
  - @coach_clinic_registrations.each do |coach_clinic_registration|
    %tr
      %td= coach_clinic_registration.name
      %td= coach_clinic_registration.program
      %td= coach_clinic_registration.email
      %td= coach_clinic_registration.comments
      %td= link_to 'Show', coach_clinic_registration
      %td= link_to 'Edit', edit_coach_clinic_registration_path(coach_clinic_registration)
      %td= link_to 'Destroy', coach_clinic_registration, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to "Admin Home", admin_path

app/views/coach_clinic_registrations/new.html.haml
#title
  Coaches Clinic Registration

= render 'form'

app/views/coach_clinic_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @coach_clinic_registration.name %>
</p>

<p>
  <b>Program:</b>
  <%= @coach_clinic_registration.program %>
</p>

<p>
  <b>Email:</b>
  <%= @coach_clinic_registration.email %>
</p>

<p>
  <b>Comments:</b>
  <%= @coach_clinic_registration.comments %>
</p>


<%= link_to 'Edit', edit_coach_clinic_registration_path(@coach_clinic_registration) %> |
<%= link_to 'Back', coach_clinic_registrations_path %>